### ISSUE TITLE
RunAll_This.sh fails looking for hard-coded path

### ISSUE THREAD

**Issue by gabbard** [qiangning/TemProb-NAACL18#3]
When running `RunAll_This.sh` as directed, most jobs fail with:

```
Unable to read from file /home/qning2/Research/EventRelationIAI/data/EventCausalityData/keys/eval.keys
```

I can't find any reference to `eval.keys` or `EventCausalityData` in this repository, so perhaps the hard-coded path is in one of the dependencies?

**Comment by gabbard** [comment]
It doesn't help with the hard-coding, but it looks like the data it is looking for is the data set for "Q. Do and Y. Chan and D. Roth, Minimally Supervised Event Causality Identification. EMNLP (2011)", which can currently be found at https://cogcomp.org/page/resource_view/27

**Comment by qiangning** [comment]
I've fixed this via [this commit](https://github.com/qiangning/TemProb-NAACL18/commit/28a3719d90fa87cf2cd99cb85ca9679cff6692ea) and tested from scratch.

**Comment by qiangning** [comment]
BTW, the dataset you found from Quang Do's paper is exactly the same with what I'm using, but maybe it's good to update your repo just in case.

**Comment by FairyGirlz** [comment]
At present, the experiment I am doing needs to use the data set of EventCausalityData, but the original directory can't be found. Could you please share this public data set with me? I would be very grateful if you could.

**Comment by qiangning** [comment]
Hi @FairyGirlz. Thanks for your report. I have found the original EventCausalityData and uploaded it in this commit: https://github.com/qiangning/TemProb-NAACL18/commit/765292068cd677d865094dce23d211b142ff95e1

However, I do remember that I have the dataset already stored in here https://github.com/qiangning/TemProb-NAACL18/tree/master/data/Quang/all_causality_data. What I did was only adding a `.tml` suffix to those files. Please let me know if this solves your problem.
